= E-Commerce Service API Documentation
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
== Overview

E-Commerce 서비스의 REST API 문서입니다.

[[user-point]]
== User Point API

=== 사용자 포인트 조회
operation::user-point_get/get-user-point[snippets='curl-request,http-request,http-response']

==== 실패 케이스: 파라미터 누락
operation::user-point_get/get-user-point_파라미터누락_-bad-request[snippets='curl-request,http-request,http-response']

=== 사용자 포인트 충전

==== 성공 케이스
operation::charge-user-point-request/charge-user-point_성공[snippets='curl-request,http-request,http-response']

==== 실패 케이스: 0원 충전
operation::charge-user-point-request/charge-user-point_0원충전[snippets='curl-request,http-request,http-response']

==== 실패 케이스: 존재하지 않는 사용자
operation::charge-user-point-request/charge-user-point_유저없음[snippets='curl-request,http-request,http-response']

==== 실패 케이스: 음수 금액
operation::charge-user-point-request/charge-user-point_음수금액[snippets='curl-request,http-request,http-response']

[[coupon]]
== Coupon API

=== 쿠폰 생성
operation::coupon-controller-test/create-coupon[snippets='curl-request,http-request,http-response,request-body,response-body']

=== 쿠폰 목록 조회
operation::coupon-controller-test/get-coupon-list[snippets='curl-request,http-request,http-response,request-body,response-body']

=== 사용자 쿠폰 목록 조회
operation::coupon-controller-test/get-user-coupon-list[snippets='curl-request,http-request,http-response,request-body,response-body']

[[order]]
== Order API

=== 주문 생성

==== 성공 케이스
operation::order-controller-test/create-order_-success[snippets='curl-request,http-request,http-response']

==== 실패 케이스: 상품 없음
operation::order-controller-test/create-order_-fail_-no-products[snippets='curl-request,http-request,http-response']

==== 실패 케이스: 사용자 ID 없음
operation::order-controller-test/create-order_-fail_-no-user-id[snippets='curl-request,http-request,http-response']

=== 결제 처리

==== 성공 케이스
operation::order-controller-test/payment_-success[snippets='curl-request,http-request,http-response']

==== 실패 케이스: 주문 ID 없음
operation::order-controller-test/payment_-fail_-no-order-id[snippets='curl-request,http-request,http-response']

==== 실패 케이스: 사용자 ID 없음
operation::order-controller-test/payment_-fail_-no-user-id[snippets='curl-request,http-request,http-response']

[[product]]
== Product API

=== 인기 상품 조회
operation::product-controller-test/get-hot-products_-success[snippets='curl-request,http-request,http-response']

=== 카테고리별 상품 조회
operation::product-controller-test/get-products_-with-category[snippets='curl-request,http-request,http-response']

=== 전체 상품 조회
operation::product-controller-test/get-products_-without-category[snippets='curl-request,http-request,http-response']